### ISSUE TITLE
Test new deployment pipeline

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/assessments#115]
This issue is purely to test the new deployment pipeline. Feel free to ignore.

We will be checking that:
- [x] Pull request. Creating and updating a PR causes the `test` job to run and, if requested, deploys a preview url
- [x] Pull request. Updating the PR comment to include PREVIEW:DEVELOP deploys a preview to the develop environment
- [x] Pull request. Updating the PR comment to include PREVIEW:STAGING deploys a preview to the staging environment
- [x] Pull request. Updating the PR comment to include PREVIEW:OFF does not deploy a preview
- [x] Merge. Merging a PR into `main` bumps the package version number (if not already bumped)
- [x] Merge. Merging a PR into `main` causes draft release notes to be updated
- [x] Merge. Merging a PR into `main` deploys the latest draft to staging
- [x] Publishing a draft release deploys the latest to production
- [x] Using manual workflow `Deploy to Production` we can roll back to a previous version
- [x] Using manual workflow `Deploy to Production` we can roll forwards to another version

**Comment by warrensearle** [comment]
Hey @tomlovesgithub and @mbrookeswebdev I wonder if you would each test the above on Assessments.
In my testing I just made a change to the readme.md file (included an extra line break) in order to create the PR and take it through the pipeline.

**Comment by mbrookeswebdev** [comment]
@warrensearle 

Tom and I both tested it, for me most steps worked but I have a few questions with regards to the process:

1. What should we see if PREVIEW:OFF is selected? I've had a staging preview url from the previous step and when I chose PREVIEW:OFF nothing happened, the staging url was still displaying. I thought it might disappear if it is OFF.

2. What should happen after the rollback process is complete? We've run the workflow to rollback to 0.14.0 from 0.15.0 and current release still shows 0.15.0 and nothing seemed have changed(?).
