### ISSUE TITLE
Upgrade to VueJS v3

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/assessments#174]
Our admin app has recently been upgraded by @drieJAC to use Vue 3 instead of Vue 2.

Lessons learned and some useful pointers have been documented here:
https://github.com/jac-uk/admin/blob/main/VUE3_UPGRADE.md

Please upgrade our Assessments app to use Vue 3 instead of Vue 2.

**Estimate:**
Large (5-10 days)

**Note**: 
 - Refer to the upgrade notes (and source code) in Admin for any help
 - @tomlovesgithub will be upgrading Assessments app and @halcyonJAC will be upgrading Apply so please do talk to each other and co-ordinate efforts if you like
 - @drieJAC is also available to help answer any questions or advise on best path forwards

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/assessments/174?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle
