### ISSUE TITLE
 Upgrade Assessments Platform to use the latest Firebase library

### ISSUE THREAD

**Issue by Franceswog** [jac-uk/assessments#178]
Following the upgrade of Admin repo, we need to upgrade the other repos to the latest version.

Useful links

https://firebase.google.com/docs/web/modular-upgrade

- [ ] [jac-kit] Upgrade Firebase SDK to latest stable version
- [ ] [admin] Upgrade Firebase SDK to latest stable version
- [ ] Refactoring Authentication functions to modular APIs
- [ ] Refactoring Firestore functions to modular APIs
- [ ] Refactoring Firestore Action
- [ ] Update Firestore Action in store/*.js files

**Comment by Franceswog** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/assessments/178?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by warrensearle** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/assessments/178?planning-poker) with Zenhub @KoWeiJAC
