### ISSUE TITLE
Upgrade to Node 20

### ISSUE THREAD

**Issue by HalcyonJAC** [jac-uk/assessments#183]
Upgrade to Node 20 to fix the Github action.

<img width="1757" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThVQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0d92a30f8907c23251ddc87912768f642c70cff/image.png" alt="image.png" />

**Comment by nickaddy** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Platform-Development-5ea838cd2aec471eb6d14139/issues/jac-uk/assessments/183?planning-poker) with Zenhub @drieJAC @HalcyonJAC @tomlovesgithub @warrensearle

**Comment by nickaddy** [comment]
@HalcyonJAC Is this the latest version?

**Comment by HalcyonJAC** [comment]
The latest long-term support (LTS) version is `22`. In other repos we have upgraded them to `20`.
