### ISSUE TITLE
Display multiple files

### ISSUE THREAD

**Issue by crablab** [jac-uk/assessments#24]
It is possible to upload multiple files for an independent assessment. 

This is done to provide different IA templates, dependant on who the assessors are. Only one template will be filled in and submitted. 

Unfortunately, we only show one of the multiple IA templates uploaded in `admin`. 

`exercise.downloads.independentAssessors` contains the array of the IAs uploaded, however when we create the assessments only a single file is copied to `assessment.exercise.template`

**Comment by warrensearle** [comment]
@ClaireTroughtonJAC please confirm that you'd like the assessments app to support there being multiple templates to download. It makes sense, unless there's a clever way to match an assessor with their appropriate template.

**Comment by crablab** [comment]
Discussed this morning and confirmed this is an issue with `admin`, and only one IA form can be uploaded.
