### ISSUE TITLE
Inconsistent link destination for assessors 

### ISSUE THREAD

**Issue by crablab** [jac-uk/assessments#26]
When opening an IA link, sometimes the assessor will end up on the page for the assessment, and sometimes on the page listing all of their outstanding assessments. 

Expected: if they only have one assessment outstanding, the link should take them directly to that assessment :) 

This could be a race condition, or some kind of unexpected functionality (ie. we're counting total IAs for the assessor, not those outstanding)

**Comment by warrensearle** [comment]
This appears to be fixed by the work carried out in #34

**Comment by crablab** [comment]
Fixed :)
