### ISSUE TITLE
`+` being stripped from emails in IA links

### ISSUE THREAD

**Issue by crablab** [jac-uk/assessments#28]
Issue: the `+` symbol is being stripped from email addresses at some point between the link being clicked on in the IA email, and the email being sent to the backend. This causes an unhandled exception. 
![image.png](https://images.zenhubusercontent.com/5ee73e89ae6caf2243b458bb/8c4ec479-901e-4870-941e-b6f74fd04b28)

Expected: emails with a `+` in them are valid. We should fix this.

**Comment by warrensearle** [comment]
Hey @crablab this looks like a UI issue. Please could you investigate and let me know.

**Comment by warrensearle** [comment]
Actually think this might be solved in the back-end by encoding the email address using `encodeUriComponent()`... but be good to know if there's a UI-based fix too

**Comment by crablab** [comment]
As discussed, backend bug in emails. @warrensearle to look at in Digital Platform :smile:

**Comment by warrensearle** [comment]
Will look at this in the digital platform however in the meantime I've applied a very quick fix to the UI which does the job.
