### ISSUE TITLE
Clicking on the `< back` button on /assessment/{id}/upload goes to sign in 

### ISSUE THREAD

**Issue by crablab** [jac-uk/assessments#30]
Issue: after opening the link in the email the user is redirected to `/assessment/{id}/upload`. Clicking on the back button in the page takes them to the sign in page. 

Expected: logically this should take them back to `/assessments` (since they are already logged in), or we should add a separate button to go to `/assessments` and make the back button do nothing.

**Comment by crablab** [comment]
@warrensearle What do you think of something lie [this](https://forum.vuejs.org/t/how-to-go-back-or-go-home/30242/4) as a solution? 
We check where you came from and if it was the sign in page, we send you to the list of assessments?

**Comment by warrensearle** [comment]
An alternative might be:
- Change the 'back' link to 'assessments', say
- We only show the 'assessments' link if the user has other assessments

**Comment by crablab** [comment]
I think that might be a neater solution :smile:  As we don't have nested pages there is no need to provide any additional functionality here. 

I think for simplicity we could always show this link, as otherwise we're going to have to load all of the user's assessments to know whether we need to show that link or not, which I don't think we currently do on that page. 

Do you think that's an acceptable compromise? :smile:

**Comment by warrensearle** [comment]
Deal! I think that's better anyway. The users will always have at least one assessment so why not get them used to there being a place where they can see all their assessments.
