### ISSUE TITLE
Following a log-in link does not end & replace the previous user session

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/assessments#34]
When logged in as user A, if we follow a log in link for user B we remain logged in as user A.
In order to continue as user B this means there's a need for the assessor to log out before they try to log in.

This will be confusing where an assessor has multiple email addresses, say, or where they are using a shared computer with another assessor.

**Actual**
When logged in as user A, if we follow a log in link for user B we remain logged in as user A

**Expected**
When logged in as user A, if we follow a log in link for user B we should be logged in as user B

**Comment by crablab** [comment]
Proposed fix to ensure we clear local storage whenever the `log-in` page is hit. This will force the user to re-authenticate every time they use a sign-in link

**Comment by warrensearle** [comment]
Looks like the changes here also fix #35 and #26

**Comment by crablab** [comment]
Fixed :)
