### ISSUE TITLE
Check load time for logging in an assessor

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/assessments#36]
When following an email login link the user is directed through a sequence of pages before they arrive at the Assessment page.

It has been noted that sometimes this appears to be rather slow. We should measure the load time from start (click link) to end (assessment page loaded) for this journey and identify any steps that could be optimised.

Note: this may be related to our assessments store loading all assessments for the assessor. The following ticket might help to speed up the assessments store assessments#33. Alternatively we may wish to consider when the assessments store should be loaded.
Note also that Cloud Functions have a longer start-up time on first run (cold start)

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle assume this is still relevant? Did it form part of Friday's testing?

**Comment by Rebecca-mcknight1991** [comment]
@londonprojects is analytics installed on assessments repo. If so can you shed any timings light on how long it takes?

**Comment by Rebecca-mcknight1991** [comment]
@londonprojects anything on this?
