### ISSUE TITLE
Possible to view the other half of the IA when logged in as an assesor 

### ISSUE THREAD

**Issue by crablab** [jac-uk/assessments#41]
When I am logged in as assessor `-1`, I can change the URL to `-2` and view the other half of the assessment, and vice versa. 

We should ensure that assssors can't see the opposing half of an IA.

**Comment by crablab** [comment]
@warrensearle Are you working on this at the moment? :smile:

**Comment by warrensearle** [comment]
Hey @crablab yes am looking into this one

**Comment by crablab** [comment]
@warrensearle I tried to reproduce this again today and couldn't - is this a change you've made? :smile:

**Comment by warrensearle** [comment]
Can you confirm the email address you used when you saw this issue? I suspect it was a JAC address.
As things stand JAC email addresses can view any assessment document.
Any other email address should only have access to their own assessment documents (i.e. where the email address in the document matches their own)

**Comment by crablab** [comment]
That would explain it then :smile:  Thanks!

**Comment by warrensearle** [comment]
Going to close this issue
