### ISSUE TITLE
 Add 'Export to Google Sheets' cloud function.

### ISSUE THREAD

**Issue by tomlovesgithub** [jac-uk/assessments#64]
Callable by admin #802, eventually triggered by database events (e.g. a QT closing).

**Comment by Rebecca-mcknight1991** [comment]
@warrensearle I've closed the export to google sheets so can close this right?

**Comment by warrensearle** [comment]
Yes this can be closed. It’s also on the assessments repo, and sounds like a platform feature, so can be double-closed
