### ISSUE TITLE
Assessors should get a clear message when 'replacing' a file

### ISSUE THREAD

**Issue by Rebecca-mcknight1991** [jac-uk/assessments#67]
As an Assessor/Admin I am frustrated that when I replace a document on the Assessments I do not get a clear confirmation message. 

When you replace the file a green banner should appear confirming submission. It might even say 'Replacement successful' to be 100% clear. 

Feedback from Alza.

**Comment by warrensearle** [comment]
For now when a user chooses to replace an uploaded file let's change the message to say "Your file has been replaced"

**Comment by warrensearle** [comment]
Checked with @Rebecca-mcknight1991 and this is working as expected, so moving to Reviewed.
A separate bug was spotted during testing which is captured in #65 so is outside scope of this ticket.
