### ISSUE TITLE
Manual testing of Assessments

### ISSUE THREAD

**Issue by warrensearle** [jac-uk/assessments#68]
There have been a number of issues reported with Assessments. Let's take some time to aggressively test, document any bugs and then fix.

We are not testing the admin journey nor the Notify email sending. Our journey starts once the Assessor has received an email containing a link to upload their assessment.

The Assessor should be able to follow the link, view instructions for what they need to do, download a template, upload their assessment and submit it. Each assessment has a due date and a hard limit date. An assessor should be able to upload before and after the due date but not after the hard limit date. [TODO: we need to better document the scenarios and expected journeys here]

The format of the link that's emailed to the assessor is:
```
ASSESSMENTS_URL + '/sign-in?email=' + EMAIL + '&ref=assessments/' + ASSESSMENT_ID 
```

Note: See documentation#18 for more info on documenting the journey being tested and on capturing the results.

**Comment by lloback** [comment]
WE tested thoroughly the Assessments on the sprint. I am closing this task.
If some other test is needed on another sprint we should create a new task and story point it accordingly.
